#+title: fzf-posframe
#+author: Naoya Yamashita

[[https://github.com/conao3/fzf-posframe.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/fzf-posframe.el.png]]

[[https://github.com/conao3/fzf-posframe.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/fzf-posframe.el.svg?style=flat-square]]
[[https://github.com/conao3/fzf-posframe.el/releases][https://img.shields.io/github/tag/conao3/fzf-posframe.el.svg?style=flat-square]]
[[https://github.com/conao3/fzf-posframe.el/actions][https://github.com/conao3/fzf-posframe.el/workflows/Main%20workflow/badge.svg]]

Display fzf in a floating posframe window for Emacs.

* Overview

[[https://github.com/conao3/fzf-posframe.el][https://raw.githubusercontent.com/conao3/files/master/blob/fzf-posframe.el/fzf-posframe.gif]]

fzf-posframe provides a clean, centered display for [[https://github.com/junegunn/fzf][fzf]] fuzzy finder results using [[https://github.com/tumashu/posframe][posframe]]. Instead of splitting your window, fzf appears in an elegant floating frame that stays out of your way.

** Features

- Display fzf results in a floating posframe
- Multiple positioning options (frame-center, window-center, point, and more)
- Customizable dimensions, font, and border styling
- Seamless integration with existing fzf workflows

** Requirements

- Emacs 26.1 or later
- [[https://github.com/bling/fzf.el][fzf.el]] 0.2 or later
- [[https://github.com/tumashu/posframe][posframe]] 0.8.5 or later
- [[https://github.com/junegunn/fzf][fzf]] command-line tool

* Installation

** Using package.el

#+begin_src emacs-lisp
(package-install 'fzf-posframe)
#+end_src

** Using leaf.el

#+begin_src emacs-lisp
(leaf fzf-posframe
  :ensure t
  :global-minor-mode fzf-posframe-mode)
#+end_src

** Using use-package

#+begin_src emacs-lisp
(use-package fzf-posframe
  :ensure t
  :config
  (fzf-posframe-mode 1))
#+end_src

* Usage

Enable the global minor mode to start using fzf-posframe:

#+begin_src emacs-lisp
(fzf-posframe-mode 1)
#+end_src

Once enabled, all fzf commands will automatically display in a posframe.

* Customization

** Display Position

Control where the posframe appears with =fzf-posframe-style=:

#+begin_src emacs-lisp
(setq fzf-posframe-style 'frame-center)  ; Default: center of frame
#+end_src

Available styles:
- =frame-center= - Center of the frame (default)
- =window-center= - Center of the current window
- =point= - Near the cursor position
- =window-bottom-left= - Bottom left of window
- =frame-bottom-left= - Bottom left of frame
- =frame-bottom-window-center= - Bottom of frame, horizontally centered in window

** Dimensions

#+begin_src emacs-lisp
(setq fzf-posframe-width 80)       ; Width in characters
(setq fzf-posframe-height 20)      ; Height in lines
(setq fzf-posframe-min-width 30)   ; Minimum width
(setq fzf-posframe-min-height 20)  ; Minimum height
#+end_src

** Appearance

#+begin_src emacs-lisp
(setq fzf-posframe-font "Monospace-12")  ; Custom font
(setq fzf-posframe-border-width 1)        ; Border width (0 for no border)
#+end_src

Customize faces for colors:

#+begin_src emacs-lisp
(set-face-attribute 'fzf-posframe nil
                    :background "#282a36"
                    :foreground "#f8f8f2")

(set-face-attribute 'fzf-posframe-border nil
                    :background "#6272a4")
#+end_src

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests on [[https://github.com/conao3/fzf-posframe.el][GitHub]].

** Development Setup

Install [[https://github.com/conao3/keg.el][keg]] for testing:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Workflow

#+begin_src shell
git checkout -b your-feature-branch
# Make your changes
make test
git commit -am "Add your feature"
git push origin your-feature-branch
# Open a pull request
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/fzf-posframe.el/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
